xaviergonz/mobx-keystone

- packages/lib/package.json
The ESM bundle filename in `packages/lib/package.json` does not match the actually built filename and there is a reference to a UMD bundle which currently is not built. Would you like to build a UMD bundle, too? This needs to be explicitly enabled since [TSDX v0.7.0](https://github.com/palmerhq/tsdx/releases/tag/v0.7.0).
> Fix ESM bundle filename and remove UMD bundle reference

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/model/BaseModel.ts
- packages/lib/src/model/Model.ts
- packages/lib/src/model/getModelDataType.ts
- packages/lib/src/model/modelDecorator.ts
- packages/lib/src/model/newModel.ts
> try to fix inheritance for es6

- CHANGELOG.md
- README.md
- packages/benchmark/package.json
- packages/lib/package.json
- packages/lib/src/action/builtInActions.ts
- packages/lib/src/action/hookActions.ts
- packages/lib/src/action/index.ts
- packages/lib/src/action/modelFlow.ts
- packages/lib/test/action/flow.test.ts
- packages/lib/test/actionMiddleware/actionTrackingMiddleware-flow.test.ts
- packages/lib/test/actionMiddleware/transactionMiddleware.test.ts
- packages/site/package.json
- packages/site/src/intro.mdx
- packages/site/src/models.mdx
- yarn.lock
[BREAKING CHANGE] Using flows in TypeScript should result in improved typings, but it requires TypeScript >= 3.6.2. Check the updated flow section of the documentation to see how to work with them now.
Scheduled for 0.15.0
> better flow typings

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/snapshot/internal.ts
- packages/lib/src/tweaker/core.ts
- packages/lib/src/tweaker/tweak.ts
- packages/lib/src/tweaker/tweakArray.ts
- packages/lib/src/tweaker/tweakFrozen.ts
- packages/lib/src/tweaker/tweakModel.ts
- packages/lib/src/tweaker/tweakPlainObject.ts
- packages/lib/test/model/onChildAttachedTo.test.ts
- packages/lib/test/spread/spread.test.ts
- Better support for array / object spreading, reassing to filter/map, etc. Objects and arrays will be automatically unconverted from tree nodes when detached.
Basically stuff such as
```
this.todos = [...this.todos, newTodo]
this.todos = this.todos.filter(t => t.done)
```
Now will work without complaining that the objects were already in the tree and already had a parent. (Note that it is usually recommended to use mutable methods to generate smaller patches though)
> better spreading support

- packages/site/src/contexts.mdx
The node instance `this` was missing in `usernameCtx.setComputed(this, () => this.username)` in the docs section about contexts.
I also fixed a few other minor typos.
> Minor fixes in docs on contexts

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/model/Model.ts
- packages/lib/src/model/newModel.ts
- packages/lib/src/model/prop.ts
- packages/lib/src/typeChecking/TypeChecker.ts
- packages/lib/src/typeChecking/array.ts
- packages/lib/src/typeChecking/arraySet.ts
- packages/lib/src/typeChecking/model.ts
- packages/lib/src/typeChecking/object.ts
- packages/lib/src/typeChecking/objectMap.ts
- packages/lib/src/typeChecking/or.ts
- packages/lib/src/typeChecking/record.ts
- packages/lib/src/typeChecking/ref.ts
- packages/lib/src/typeChecking/refinement.ts
- packages/lib/src/typeChecking/resolveTypeChecker.ts
- packages/lib/src/typeChecking/schemas.ts
- packages/lib/src/typeChecking/tProp.ts
- packages/lib/src/typeChecking/typeCheck.ts
- packages/lib/test/typeChecking/typeChecking.test.ts
- packages/site/src/runtimeTypeChecking.mdx
- yarn.lock
Fixes #39 
You can also do `tProp(defaultValue: string | number | boolean)`, which is equivalent to `tProp(types.string|number|boolean, defaultValue)`.
In other words, if you use `tProp(42)`, then the property will be a number that takes the value `42` when undefined.
> tProp syntax sugar

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/action/applyAction.ts
- packages/lib/src/actionMiddlewares/actionSerialization/applySerializedAction.ts
- packages/lib/src/actionMiddlewares/actionSerialization/index.ts
- packages/lib/src/actionMiddlewares/index.ts
- packages/lib/src/globalConfig/globalConfig.ts
- packages/lib/src/model/BaseModel.ts
- packages/lib/test/actionMiddleware/applySerializedAction.test.ts
- packages/lib/test/model/ids.test.ts
- packages/site/package.json
- packages/site/src/actionMiddlewares/onActionMiddleware.mdx
- packages/site/src/examples/clientServer/appInstance.tsx
- packages/site/src/examples/clientServer/server.ts
- packages/site/src/references.mdx
- yarn.lock
- Added `applySerializedActionAndTrackNewModelIds` and `applySerializedActionAndSyncNewModelIds`. Prefer those over `deserializeActionCall` plus `applyAction` when applying serialized (over the wire) actions in order to avoid \$modelId desynchronization.
- Added a default implementation of `getRefId()` which returns `$modelId`.
*This only affects people using action serialization+replication between different machines. If just using actions locally `applyAction` is still very much ok*
Basically after adding model ids + checks on apply action to make sure the path ids are applied over the proper I realized that:
- if models get created inside an action being run on the server, then these models would get ids A, B, C
- if action then gets replicated on client, models get created as well, …
> add applySerializedAction methods

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/ref/core.ts
- packages/lib/test/ref/rootRef.test.ts
> Fixed an issue with back-references and `onResolvedValueChange` not working when references were being restored from a snapshot.

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/model/BaseModel.ts
- packages/lib/test/model/subclassing.test.ts
- packages/site/src/models.mdx
- [BREAKING CHANGE] If you want to use `ExtendsModel` over an abstract class now it must be done like `ExtendsModel(abstractModelClass(SomeAbstractClass), { ... })`.
> better abstract model class support

- packages/lib/package.json
- yarn.lock
In 575bac559f3065a6fd86cabf8f2b153649bb1e7e the new assertion syntax introduced in TS 3.7 is used, but `packages/lib/package.json` still requires only [`^3.6.4`](https://github.com/xaviergonz/mobx-keystone/blob/376aa2df28b3272a0652a6ba545e70066f279e67/packages/lib/package.json#L56). The error hasn't surfaced because TS 3.7 is locked in `yarn.lock`.
> Require Typescript 3.7 to support new assertion syntax

- CHANGELOG.md
- packages/lib/src/actionMiddlewares/readonlyMiddleware.ts
- packages/lib/src/treeUtils/index.ts
- packages/lib/src/treeUtils/sandbox.ts
- packages/lib/test/treeUtils/sandbox.test.ts
- packages/site/doczrc.js
- packages/site/src/sandbox.mdx
In continuation of our discussion in #73, this is a first attempt at creating a middleware for managing a draft copy of a tree for efficient testing of changes that can be applied to the original tree or rejected.
In most cases, the middleware must be applied to the root of a tree, e.g. in order to support `rootRef` resolution in the draft as well. When the middleware is applied to a root store, the draft is also registered as a root store.
In order to access `withDraft` anywhere in a tree, I would provide `DraftManager` using a context.
> Sandbox function

- CHANGELOG.md
- packages/lib/src/actionMiddlewares/transactionMiddleware.ts
- packages/lib/src/actionMiddlewares/undoMiddleware.ts
- packages/lib/src/patch/applyPatches.ts
- packages/lib/src/treeUtils/sandbox.ts
- packages/lib/src/tweaker/typeChecking.ts
- packages/lib/test/patch/applyPatches.test.ts
- packages/lib/test/patch/patch.test.ts
- packages/site/src/patches.mdx
I noticed that [inverse patches are recorded in the same order as patches](https://github.com/xaviergonz/mobx-keystone/blob/e701396b461498c0bae1894d39d39531143fb14f/packages/lib/src/tweaker/tweakArray.ts#L140-L144) which means in order to revert changes by applying inverse patches, inverse patches must be applied in reverse order. To avoid something like `applyPatches(node, inversePatches.slice().reverse())`, I added a third argument `reverse: boolean = false` to `applyPatches` which causes `applyPatches` to apply patches in reverse order when `reverse === true`. I also fixed all occurrences of inverse patching to use reverse order.
Unfortunately, I wasn't able to find an operation for a test case that results in multiple patches (with `onPatches`) where applying inverse patches in the …
> Apply inverse patches in reverse order

- packages/lib/src/tweaker/tweakArray.ts
- packages/lib/test/patch/patch.test.ts
`Array.unshift` was generating unnecessarily complex patches for non-empty arrays. I added a [test that shows the current state (before this PR)](d3dd8dfb70171b43c8de4cfef84b67b24232ff48) and an [optimization to create simpler patches](7b4de75d32addc8c6ca0a3bff4f0d1860776ad86). The diff of the optimization looks more invasive than it is - all I did was to add:
```ts
// optimization, if `splice` is equivalent to `unshift` on a non-empty array
if (change.index === 0 && addedCount !== 0 && change.removedCount === 0 && oldLen !== 0) {
let i = addedCount
const path = [0]
while (i--) {
patches.push({
op: "add",
path,
value: addedItems[i],
})
invPatches.push({
op: "remove",
path,
})
}
} else {
// everything as before
}
```
I also added tests to make sure patches are as expected for …
> Optimize patches generated by Array.unshift

- CHANGELOG.md
- packages/lib/src/model/BaseModel.ts
- packages/lib/src/model/Model.ts
- packages/lib/src/model/modelDecorator.ts
- packages/lib/test/model/modelDecorator.test.ts
- Added `$modelType` as static property to model classes, as well as better `toString()` to model classes and instances for logging purposes.
Fixes #90
> better logging

- CHANGELOG.md
- packages/benchmark/package.json
- packages/lib/package.json
- packages/lib/src/model/modelDecorator.ts
- packages/lib/src/parent/coreObjectChildren.ts
- packages/lib/src/parent/getChildrenObjects.ts
- packages/lib/src/parent/path.ts
- packages/lib/src/patch/applyPatches.ts
- packages/lib/src/snapshot/applySnapshot.ts
- packages/lib/src/snapshot/reconcileSnapshot.ts
- packages/lib/src/utils/ModelPool.ts
- packages/lib/test/patch/applyPatches.test.ts
- packages/lib/test/ref/rootRef.test.ts
- packages/lib/test/snapshot/snapshot.test.ts
- packages/site/src/patches.mdx
- yarn.lock
- `applyPatches` now supports arrays of arrays of patches.
- Improved reconciliation - now `applyPatches` and `applySnapshot` are more likely to reuse instantiated model objects whenever possible rather than recreating them anew (as long as their model types and ids match).
Fixes #116
> Improved reconciliation

- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/action/modelAction.ts
- packages/lib/src/model/Model.ts
- packages/lib/src/model/modelDecorator.ts
- packages/lib/test/model/modelDecorator.test.ts
- packages/lib/test/model/subclassing.test.ts
- packages/site/src/models.mdx
Allows the usage of the lib without decorators
Example
```ts
const Point = decoratedModel(
"decoratedModel/Point",
// although class could be anonymous, by giving it a name 
// type declarations are shorter
// and the IDE shows better typings if we do
class Point extends Model({
x: prop<number>(),
y: prop<number>(),
}) {
setX(x: number) {
this.x = x
}
setY = (y: number) => {
this.y = y
}
setXY(x: number, y: number) {
this.setX(x)
this.setY(y)
}
get length() {
return this.x + this.y
}
volatile = "volatile"
},
{
setX: modelAction,
setY: modelAction,
setXY: modelAction,
length: computed,
// multiple decorators could be applied with xxx: [deco1, deco2...]
}
)
type Point = InstanceType<typeof Point> // needed to be able to do SnapshotInOf<Point>, etc
const p = new Point<number>({ x: 10, y: 20 …
```
> decoratedModel

- CHANGELOG.md
- packages/lib/src/model/BaseModel.ts
- packages/lib/src/model/Model.ts
- packages/lib/src/propTransform/DateBackedByProp.ts
- packages/lib/src/propTransform/propTransform.ts
- packages/lib/src/propTransform/transformArrayAsMap.ts
- packages/lib/src/propTransform/transformArrayAsSet.ts
- packages/lib/src/propTransform/transformObjectAsMap.ts
- packages/lib/src/propTransform/transformStringAsDate.ts
- packages/lib/src/propTransform/transformTimestampAsDate.ts
- packages/lib/src/utils/lock.ts
- packages/lib/test/propTransform/decorator/stringAsDate.test.ts
- packages/lib/test/propTransform/decorator/timestampAsDate.test.ts
- packages/lib/test/propTransform/implicit/transformArrayAsMap.test.ts
- packages/lib/test/propTransform/implicit/transformArrayAsSet.test.ts
- packages/lib/test/propTransform/implicit/transformObjectAsMap.test.ts
- packages/lib/test/propTransform/implicit/transformStringAsDate.test.ts
- packages/lib/test/propTransform/implicit/transformTimestampAsDate.test.ts
- packages/site/src/mapsSetsDates.mdx
- When using date transforms, mutation made by methods (`setTime`, etc.) are reflected in the backed property (string / timestamp), so it is no longer required to treat dates as immutable objects.
- Performance improvements for implicit property transform collections.
> Improve implicit properties collection speed, Date mutability

- README.md
- packages/site/src/intro.mdx
I just fixed a couple of typos and made a few minor language improvements. I also synced the docs introduction page with the README file.
> Fix typos and improve wording in README and docs introduction

- packages/lib/src/typeChecking/refinement.ts
- packages/lib/test/typeChecking/typeChecking.test.ts
A refinement type error always had the path `[]` even when the refinement type was used as a child of another type, e.g. `types.object`. I've added a test and fixed the refinement type to use the path passed to the check function instead.
> Fix TypeError path of refinement type

- CHANGELOG.md
- packages/lib/src/treeUtils/sandbox.ts
- packages/lib/test/treeUtils/sandbox.test.ts
When committing multiple changes made in a sandbox to the original tree, multiple items in the undo manager's queue were created so that a single call to `undoManager.undo()` did not undo the commit. I think this behavior is not intuitive and unintended.
I've fixed the sandbox to apply the commit patches in a single action, so a single undo item is created for the entire commit.
> Fix grouping sandbox commit patches in a single undo item

- CHANGELOG.md
- packages/lib/src/treeUtils/sandbox.ts
- packages/lib/test/treeUtils/sandbox.test.ts
- packages/site/src/sandbox.mdx
This PR contains an (in my opinion) improvement of the sandbox API.
The sandbox manager's `withSandbox` method now requires an array of nodes from the original tree and the corresponding sandbox nodes are now positional arguments of the callback function. E.g.:
```ts
// before
sandboxManager.withSandbox(a, (sa) => { ... })
// after
sandboxManager.withSandbox([a], (sa) => { ... })
// before
sandboxManager.withSandbox([a, b], ([sa, sb]) => { ... })
// after
sandboxManager.withSandbox([a, b], (sa, sb) => { ... })
```
Note that this PR contains a breaking change in the signature of the `withSandbox` method.
@xaviergonz What do you think? I hope a minor breaking change in this isolated feature is okay.
> Improve sandbox manager API

- CHANGELOG.md
- packages/lib/src/treeUtils/sandbox.ts
- packages/lib/test/treeUtils/sandbox.test.ts
I discovered a bug where committing non-idempotent changes in the sandbox to the original subtree resulted in an incorrect sandbox state. The problem was that applying the sandbox patches to the original subtree triggered the `onPatches` listener that applies changes in the original subtree to the sandbox to keep them in sync. When committing changes in the sandbox to the original subtree, the patches emitted in the original subtree should be ignored by the sandbox.
This PR fixes the bug.
> Fix committing non-idempotent sandbox changes to the original subtree

- packages/lib/src/patch/patchRecorder.ts
- packages/site/src/patches.mdx
Just a minor typo fix in the `PatchRecorderOptions` interface docs.
> Fix typo in patch recorder docs

- .vscode/settings.json
- CHANGELOG.md
- packages/lib/package.json
- packages/lib/src/dataModel/DataModel.ts
- packages/lib/src/model/BaseModel.ts
- packages/lib/src/model/Model.ts
- packages/lib/src/model/newModel.ts
- packages/lib/src/model/utils.ts
- packages/lib/src/modelShared/BaseModelShared.ts
- packages/lib/src/modelShared/Model.ts
- packages/lib/src/snapshot/SnapshotOf.ts
- packages/lib/src/snapshot/applySnapshot.ts
- packages/lib/src/snapshot/getSnapshot.ts
- packages/lib/src/snapshot/internal.ts
- packages/lib/src/snapshot/reconcileModelSnapshot.ts
- packages/lib/src/tweaker/tweakArray.ts
- packages/lib/src/tweaker/tweakFrozen.ts
- packages/lib/src/tweaker/tweakPlainObject.ts
- packages/lib/src/utils/ModelPool.ts
- packages/lib/test/model/modelDecorator.test.ts
- packages/lib/test/snapshot/processor.test.ts
- packages/site/src/classModels.mdx
- packages/site/src/snapshots.mdx
- [BREAKING CHANGE] The model override `fromSnapshot` has been removed in favor of `fromSnapshotProcessor` / `toSnapshotProcessor` for `Model` / `ExtendedModel`. These allow you to set up pre/post snapshot processors for models.
`fromSnapshotProcessor` might be used to transform an input snapshot into the model expected input snapshot.
This is useful for example for versioning.
Note that the `$modelType` property will always be there and will remain unchanged no matter the transformation.
```ts
@model("name")
class Name extends Model(
{
// in version 2 we split fullName into firstName and lastName
_version: prop(2),
firstName: prop<string>(),
lastName: prop<string>(),
},
{
fromSnapshotProcessor(
sn: { _version: 2; firstName: string; lastName: string } | { _version: 1; fullName: string }
) …
```
> add snapshot processors for class models

- packages/site/src/standardAndStandaloneActions.mdx
Just a minor improvement (IMO) regarding navigation across the docs pages.
> add link to undo middleware in standalone actions docs

- packages/site/src/patches.mdx
Since the behavior of `onPatches` and, e.g., `onSnapshot` or a MobX reaction differs with regard to when the listener is called, I think it's worth adding a note about it in the docs.
> add note to docs when onPatches listener is called

- packages/site/src/drafts.mdx
- packages/site/src/mstComparison.mdx
- packages/site/src/rootStores.mdx
- packages/site/src/sandbox.mdx
Since `withSetter()` should be the standard way of defining setters in my opinion unless a non-standard setter is needed, I think it should be preferred in the docs where applicable to promote its usage. I intentionally left `classModels.mdx` and `dataModels.mdx` untouched because those pages introduce `withSetter()` and for that reason should keep manually defined setters.
> prefer using generated setter in docs

- packages/site/src/references.mdx
Fixed a minor code formatting error in `references.mdx`.
> fix code formatting in references docs

- packages/site/src/patches.mdx
The fix is two-fold:
1. `patchRecorder` does not have a third argument `onPatches`, it's actually part of the `opts` argument.
2. The expanded `opts` argument type is a bit verbose and the `PatchRecorderOptions` interface is shown below anyway, so for better readability and consistency with the documentation of other functions, I've replaced the expanded type by the `PatchRecorderOptions` type.
> fix patchRecorder signature in docs

- packages/site/docs/actionMiddlewares/customMiddlewares.mdx
- packages/site/docs/actionMiddlewares/onActionMiddleware.mdx
- packages/site/docs/actionMiddlewares/readonlyMiddleware.mdx
- packages/site/docs/actionMiddlewares/transactionMiddleware.mdx
- packages/site/docs/actionMiddlewares/undoMiddleware.mdx
- packages/site/docs/classModels.mdx
- packages/site/docs/contexts.mdx
- packages/site/docs/dataModels.mdx
- packages/site/docs/drafts.mdx
- packages/site/docs/examples/clientServer/clientServer.mdx
- packages/site/docs/examples/todoList/todoList.mdx
- packages/site/docs/frozen.mdx
- packages/site/docs/mapsSetsDates.mdx
- packages/site/docs/mstComparison.mdx
- packages/site/docs/patches.mdx
- packages/site/docs/reduxCompatibility.mdx
- packages/site/docs/references.mdx
- packages/site/docs/rootStores.mdx
- packages/site/docs/runtimeTypeChecking.mdx
- packages/site/docs/sandboxes.mdx
- packages/site/docs/snapshots.mdx
- packages/site/docs/standardAndStandaloneActions.mdx
- packages/site/docs/treeLikeStructure.mdx
- packages/site/sidebars.js
This PR changes the URL path style of the docs from camel-case to kebab-case.
Follow-up of #347.
> use kebab-case URL paths in docs

- .prettierignore
- package.json
- packages/site/docusaurus.config.js
- packages/site/package.json
- packages/site/src/css/custom.css
- yarn.lock
This PR adds search to the docs using [`@easyops-cn/docusaurus-search-local`](https://github.com/easyops-cn/docusaurus-search-local).
I looked at all local search solutions for Docusaurus and found this one to be the best (IMO) considering functionality, design, code quality, and maintenance.
- [`docusaurus-plugin-lunr`](https://github.com/daldridge/docusaurus-plugin-lunr) - Appears to be umaintained.
- [`docusaurus-lunr-search`](https://github.com/lelouch77/docusaurus-lunr-search) - [No support for dark mode](https://github.com/lelouch77/docusaurus-lunr-search/issues/55) yet, written in JavaScript (not TypeScript), [requires manual swizzling](https://github.com/lelouch77/docusaurus-lunr-search#how-to-use-), not actually tested. But generally looks not too bad. Might be an alternative.
- …
> add search to docs

- packages/lib/src/model/BaseModel.ts
- packages/lib/src/modelShared/prop.ts
I've replaced remaining occurrences of `O.Omit` by `Omit` for consistency. `Omit` has been used elsewhere in the library anyway and was [introduced in TS 3.5](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) which is a sufficiently old version IMO.
> use builtin Omit utility type instead of ts-toolbelt's

- packages/lib/src/types/primitiveBased/primitives.ts
Just a minor improvement to type `identityFn` properly.
> improve internal identityFn typing

- packages/lib/src/actionMiddlewares/actionSerialization/arraySerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/dateSerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/mapSerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/objectPathSerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/objectSnapshotSerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/plainObjectSerializer.ts
- packages/lib/src/actionMiddlewares/actionSerialization/setSerializer.ts
- packages/lib/src/actionMiddlewares/undoMiddleware.ts
- packages/lib/src/standardActions/arrayActions.ts
- packages/lib/src/standardActions/objectActions.ts
- packages/lib/src/utils/index.ts
- packages/lib/src/wrappers/ArraySet.ts
- packages/lib/src/wrappers/ObjectMap.ts
- packages/lib/test/actionMiddlewares/actionSerialization.test.ts
Just a minor refactoring to have the built-in namespace "mobx-keystone" in a single place.
> factor out built-in namespace into a constant

- packages/lib/src/utils/index.ts
This PR fixes two typing issues related to the internal utility function `lateVal`:
1. The generic constraint in
https://github.com/xaviergonz/mobx-keystone/blob/6900f7780b507949f768edd7801581bb11a09989/packages/lib/src/utils/index.ts#L383
was not correct. The return type is in fact not `TF` because `getter` might be a subtype of `(...args: any[]) => any` whereas the returned function merely has the same signature as `getter`.
1. The type of the `memoized` variable
https://github.com/xaviergonz/mobx-keystone/blob/6900f7780b507949f768edd7801581bb11a09989/packages/lib/src/utils/index.ts#L384
is in fact not `TF` but `TF`'s return type.
Along with the typing fixes came a slightly different implementation because TS isn't able to narrow the type of `memoized` in …
> fix internal lateVal function typing

- packages/lib/src/action/applyDelete.ts
- packages/lib/src/action/applyMethodCall.ts
- packages/lib/src/action/applySet.ts
- packages/lib/src/parent/detach.ts
- packages/lib/src/patch/applyPatches.ts
- packages/lib/src/snapshot/applySnapshot.ts
- packages/lib/src/utils/index.ts
This PR replaces uses of the internal utility function `lazy` by `lateVal` because `lateVal` is a more general version of `lazy`, so there's no need to have both.
Do you want to rename `lateVal` to `lazy` or keep it as `lateVal`?
> remove internal function lazy and use lateVal instead

- CHANGELOG.md
- packages/lib/src/actionMiddlewares/actionSerialization/actionSerialization.ts
- packages/lib/src/actionMiddlewares/actionSerialization/primitiveSerializer.ts
- packages/lib/src/utils/index.ts
- packages/lib/src/utils/types.ts
- packages/lib/test/actionMiddlewares/actionSerialization.test.ts
- packages/site/docs/actionMiddlewares/onActionMiddleware.mdx
This PR adds support for action serialization of non-JSON primitive values (`undefined`, `bigint`, and special `number` values `NaN`/`+Infinity`/`-Infinity`, but not `symbol` because I think there's no general way to serialize them) including tests.
There are likely several ways to implement it (single vs. multiple (de)serializer(s), encoding of those primitive values etc.). This is my suggestion, but feel free to request a different approach. :slightly_smiling_face:
> add action serialization for non-JSON primitive values

- packages/lib/src/snapshot/onSnapshot.ts
Just a minor thing; `typeof nodeOrFn === "function"` already narrows `nodeOrFn` to `() => T` correctly.
> remove unnecessary type assertion in onSnapshot

- packages/lib/src/actionMiddlewares/readonlyMiddleware.ts
I think this typing is simpler and more to the point. Although there's no difference in what it does in this case, is there? :thinking:
> improve readonly middleware's allowWrite typing

- packages/lib/src/actionMiddlewares/actionTrackingMiddleware.ts
Certainly a matter of taste/style, but I think enums are preferable to string literals for representing state. Feel free to prefer keeping it as it is now if you disagree. :slightly_smiling_face:
> use enum instead of string literals for action tracking middleware state

- packages/lib/src/action/context.ts
- packages/lib/src/actionMiddlewares/actionTrackingMiddleware.ts
Are you aware of any situation in which `data` should not be an object with `symbol` keys? If not, I think the typing should enforce it.
> improve [Simple]ActionContext data property typing

- .vscode/settings.json
- package.json
- yarn.lock
Not sure whether it has been the same for you, but I've been having a slightly annoying issue with auto-formatting imports for a long time. Format on save organizes my imports but removes the trailing comma in the last import of a multi-line import statement which conflicts with what Prettier expects.
I've tracked this issue to https://github.com/prettier/prettier-vscode/issues/716 where the conclusion seems to be using [`prettier-plugin-organize-imports`](https://github.com/simonhaenisch/prettier-plugin-organize-imports) and removing VS Code's built-in import organizer:
```json
"editor.codeActionsOnSave": {
"source.organizeImports": true
}
```
That's what I've done and now it works for me. What do you think?
> fix conflict between Prettier and VS Code's organize imports

- packages/lib/src/utils/index.ts
Indentation error was accidentally introduced in https://github.com/xaviergonz/mobx-keystone/pull/373.
> fix indentation

- .github/workflows/main.yml
- .prettierignore
- .vscode/extensions.json
Prettier was also unhappy with some files outside `packages/**`. I've fixed those and added a CI job to check formatting automatically.
Did the Prettier check from https://github.com/xaviergonz/mobx-keystone/pull/196 not make it intentionally or accidentally during the migration to GitHub Actions? I think a while ago, Prettier didn't support the complete TS syntax and that CI job was failing all the time (starting with https://github.com/xaviergonz/mobx-keystone/pull/220).
Feel free to to decline this PR if you don't want a CI job that checks formatting. :slightly_smiling_face:
> fix formatting and add CI job to check it

- packages/site/docs/computedTrees.mdx
Just a minor typo in the computed trees docs I overlooked.
> fix typo in computed trees docs

- .github/workflows/main.yml
- packages/lib/babel.config.js
- packages/lib/env.js
- packages/lib/jest.config.js
- packages/lib/package.json
- packages/lib/test/types/typeChecking.test.ts
- yarn.lock
This PR adds support for running the test suite with Babel in addition to `tsc` (via `ts-jest`), especially regarding decorator compatibility with Babel's transpilation.
> run tests also with Babel

- packages/site/docs/installation.mdx
- packages/site/docs/intro.mdx
- packages/site/sidebars.js
This PR adds documentation about transpiler configurations. I've intentionally not added these instructions to `README.md` because I felt it would be a bit verbose and not as nice without tabs.
> add docs on transpiler configs

- packages/lib/src/modelShared/BaseModelShared.ts
Improves the DX in many IDEs by highlighting the usage of deprecated API typically with ~~strikethrough~~ formatting.
> add @deprecated tag to deprecated code

- .github/workflows/main.yml
Just a tiny cosmetic change to the CI job name format that I had actually introduced myself. I think, e.g., `babel - mobx6` looks more consistent than `babel - MobX v6`.
> improve CI matrix job name format

- packages/lib/src/action/hookActions.ts
Just a minor internal typing fix.
That said, the `actionName as HookAction` type assertion was semantically not correct because `actionName` could be any string. On the other hand, declaring the `hookActionValues` set as `Set<HookAction>` was correct but too narrowly typed for the membership check later which led to the type assertion. I think my proposed change is more sound and doesn't require the type assertion.
> fix internal hook action typing

- packages/lib/src/action/modelFlow.ts
- packages/lib/src/dataModel/utils.ts
- packages/lib/src/frozen/Frozen.ts
- packages/lib/src/model/utils.ts
- packages/lib/src/types/TypeChecker.ts
- packages/lib/src/utils/index.ts
I think it's better style to type the type guard argument with `unknown` instead of `any`. This requires replacing bracket notation accessor syntax for checking the presence of some symbol on an object by the `in` operator to satisfy TypeScript. I think this change is correct, but please double-check.
> use "unknown" type for type guard argument

- packages/lib/src/action/isModelAction.ts
- packages/lib/src/modelShared/Model.ts
- packages/lib/src/modelShared/modelDecorator.ts
- packages/lib/src/snapshot/applySnapshot.ts
- packages/lib/src/snapshot/fromModelSnapshot.ts
I think the `in` operator is more readable and it's more type-safe (no `any` assertions).
> use "in" operator instead of comparing with "undefined"

- packages/site/babel.config.js
Use `version: "legacy"` instead of the deprecated `legacy: true` config in the docs config.
> update Babel decorator plugin config

- packages/benchmark/package.json
- yarn.lock
The benchmark was failing to compile because chalk v5.0.0 is ESM only which the build system is not yet ok with. This reverts the dependency bump back to a non ESM version which makes the benchmarks run again.
> Pin benchmark chalk dependency to pre-ESM version

- README.md
Totally subjective, but I think the reference to the docs is a bit redundant. There's this one, there's one at the bottom of the README, and there's the link in the GitHub project's "About" section in the top-right of the landing page. I think the README looks a bit cleaner without this one. But I don't insist on its removal if you feel differently. :wink:
> remove redundant docs link

- packages/lib/src/redux/redux.ts
- packages/lib/src/types/primitiveBased/enum.ts
- packages/lib/src/types/utility/refinement.ts
Both `@typeparam` and `@template` are fine, but I think it's good to stick with one and be consistent. In almost all cases, `@typeparam` was used, so that's what I went for.
> use @typeparam tag consistently

- packages/lib/src/types/typeCheck.ts
`@typename` is not recognized by TypeDoc.
> use @typeparam tag instead of unsupported @typename

- packages/lib/src/snapshot/getSnapshot.ts
- packages/lib/src/types/primitiveBased/primitives.ts
- packages/lib/src/types/utility/unchecked.ts
- packages/lib/src/utils/index.ts
Just a minor refactoring. `identityFn` was defined in several places, so I factored it out into `utils/index.ts`. One type assertion is necessary in `getSnapshot(...)` to make it work though.
> factor out internal identityFn to utils

- CHANGELOG.md
- apps/site/docs/runtimeTypeChecking.mdx
- packages/lib/src/types/types.ts
- packages/lib/src/types/utility/annotation.ts
- packages/lib/src/types/utility/tag.ts
- packages/lib/test/types/typeChecking.test.ts
Implements a proposal for adding a new type, called type.annotation, that can wrap a prop's type to provide runtime access to metadata about the prop. See discussion [here]( https://github.com/xaviergonz/mobx-keystone/issues/460).
> Issue #460 - add type.annotation

- packages/lib/src/types/utility/typesTag.ts
Version 0.69.5 uncovered a bug in the `typesTag`: the baseChecker's check function was assigned directly rather than being wrapped within another function, which caused an endlessly recursive call to the check function from within itself because it captures `this` (i.e. `this.check()` invokes `_check()`, which is `this.check()`, which invokes `_check()`...).
> Fix: tag type wrapper check func captures wrong 'this'

- packages/lib/src/computedTree/computedTree.ts
- packages/lib/test/computedTree/computedTree.test.ts
I think it was actually incorrect to untweak `oldValue` and not `entry.tweakedValue` (i.e. `oldTweakedVlaue`) because `oldValue` hasn't been tweaked. I also saw this when stepping through the code with the debugger:
https://github.com/xaviergonz/mobx-keystone/blob/e35a792789fc66734b43cbf801d93a4e29ef9bd1/packages/lib/src/computedTree/computedTree.ts#L78
didn't execute
https://github.com/xaviergonz/mobx-keystone/blob/e35a792789fc66734b43cbf801d93a4e29ef9bd1/packages/lib/src/tweaker/tweak.ts#L91-L100
WDYT, @xaviergonz?
Fixes #483. :crossed_fingers:
> fix computed tree with array of models

- packages/lib/src/parent/onChildAttachedTo.ts
`fireForCurrentChildren: false` has no effect.
I should add corresponding tests but I'm busy at the moment. ( Sorry, but the bug is really clear. The fix should definitely work 😁. )
> fix: rename `runForCurrentChildren` to `fireForCurrentChildren`
