CHANGELOG.md
packages/lib/package.json
packages/lib/src/model/BaseModel.ts
packages/lib/src/model/Model.ts
packages/lib/src/model/modelDecorator.ts
packages/lib/test/model/subclassing.test.ts

fix issue 18

---

CHANGELOG.md
packages/lib/package.json
packages/lib/src/action/index.ts
packages/lib/src/action/modelFlow.ts
packages/lib/src/index.ts
packages/lib/test/action/flow.test.ts
packages/lib/test/actionMiddleware/actionTrackingMiddleware-flow.test.ts
packages/lib/test/actionMiddleware/readonlyMiddleware.test.ts
packages/lib/test/actionMiddleware/transactionMiddleware.test.ts
packages/lib/test/actionMiddleware/undoMiddleware.test.ts
packages/lib/test/redux/connectReduxDevTools.test.ts
packages/site/src/models.mdx

- [BREAKING CHANGE] Again changes to flows so typings are better. Check the updated flow section of the documentation to see how to work with them now (should be _much_ easier).

Improved flows dx

---

packages/site/src/actionMiddlewares/customMiddlewares.mdx
packages/site/src/actionMiddlewares/onActionMiddleware.mdx
packages/site/src/actionMiddlewares/readonlyMiddleware.mdx
packages/site/src/frozen.mdx
packages/site/src/intro.mdx
packages/site/src/mapsAndSets.mdx
packages/site/src/models.mdx
packages/site/src/mstComparison.mdx
packages/site/src/patches.mdx
packages/site/src/reduxCompatibility.mdx
packages/site/src/references.mdx
packages/site/src/rootStores.mdx
packages/site/src/runtimeTypeChecking.mdx
packages/site/src/snapshots.mdx
packages/site/src/treeLikeStructure.mdx

I've fixed some typos and other small errors, added missing backticks around `undefined` etc., improved writing consistency etc.

Improve docs

---

CHANGELOG.md
packages/lib/package.json
packages/lib/src/model/modelDecorator.ts
packages/lib/src/rootStore/attachDetach.ts
packages/lib/src/tweaker/tweak.ts
packages/lib/test/rootStore/rootStore.test.ts
packages/lib/test/spread/spread.test.ts
yarn.lock

fix issue 27

---

CHANGELOG.md
packages/lib/package.json
packages/lib/src/model/Model.ts
packages/lib/src/model/newModel.ts
packages/lib/src/model/prop.ts
packages/lib/src/typeChecking/tProp.ts
packages/lib/test/model/defaultProps.test.ts
packages/lib/test/model/factory.test.ts
packages/lib/test/model/subclassing.test.ts
packages/lib/test/snapshot/snapshot.test.ts
packages/site/package.json
packages/site/src/models.mdx
packages/site/src/runtimeTypeChecking.mdx
yarn.lock

related to https://github.com/xaviergonz/mobx-keystone/issues/44

make default values also apply to null inputs

---

CHANGELOG.md
package.json
packages/lib/package.json
packages/lib/src/model/prop.ts
packages/lib/src/typeChecking/tProp.ts
yarn.lock

Fixes https://github.com/xaviergonz/mobx-keystone/issues/58

enforce object default values to use a func to generate them

---

packages/lib/src/propTransform/propTransform.ts
packages/site/src/propertyTransforms.mdx

In the documentation, it still mentions `fromDataToProp` and `fromPropToData`. I changed it to `dataToProp` and `propToData`.

Update documentation for propTransform

---

CHANGELOG.md
packages/lib/package.json
packages/lib/src/model/Model.ts
packages/lib/src/model/modelDecorator.ts
packages/lib/src/model/prop.ts
packages/lib/src/typeChecking/TypeChecker.ts
packages/lib/src/typeChecking/array.ts
packages/lib/src/typeChecking/arraySet.ts
packages/lib/src/typeChecking/enum.ts
packages/lib/src/typeChecking/maybe.ts
packages/lib/src/typeChecking/model.ts
packages/lib/src/typeChecking/object.ts
packages/lib/src/typeChecking/objectMap.ts
packages/lib/src/typeChecking/or.ts
packages/lib/src/typeChecking/primitives.ts
packages/lib/src/typeChecking/record.ts
packages/lib/src/typeChecking/ref.ts
packages/lib/src/typeChecking/refinement.ts
packages/lib/src/typeChecking/resolveTypeChecker.ts
packages/lib/src/typeChecking/schemas.ts
packages/lib/src/typeChecking/tProp.ts
packages/lib/src/typeChecking/types.ts
packages/lib/src/typeChecking/unchecked.ts
packages/lib/src/utils/index.ts
packages/lib/test/typeChecking/__snapshots__/typeChecking.test.ts.snap
packages/lib/test/typeChecking/typeChecking.test.ts
packages/site/src/runtimeTypeChecking.mdx

add getTypeInfo and runtime type info

---

CHANGELOG.md
packages/lib/src/tweaker/tweakArray.ts
packages/lib/src/tweaker/tweakPlainObject.ts
packages/lib/test/patch/patch.test.ts

fix wrong patch order inside onAttachedToRootStore

---

CHANGELOG.md
packages/lib/src/model/modelDecorator.ts
packages/lib/test/model/modelDecorator.test.ts

fix statics in model classes

---

CHANGELOG.md
packages/lib/src/actionMiddlewares/undoMiddleware.ts
packages/lib/test/actionMiddlewares/undoMiddleware.test.ts

fix undo middleware regression

---

.vscode/settings.json
CHANGELOG.md
packages/benchmark/package.json
packages/lib/package.json
packages/lib/src/action/applySet.ts
packages/lib/src/model/Model.ts
packages/lib/src/tweaker/core.ts
packages/lib/test/model/setterAction.test.ts
packages/site/package.json
yarn.lock

fix setter actions

---

CHANGELOG.md
packages/benchmark/package.json
packages/lib/package.json
packages/lib/src/model/Model.ts
packages/lib/src/typeChecking/object.ts
packages/lib/test/model/create.test.ts
packages/lib/test/typeChecking/typeChecking.test.ts
packages/site/package.json
yarn.lock

allow excess props when doing runtime type checking of objects

---

packages/lib/src/typeChecking/enum.ts
packages/lib/test/model/factory.test.ts
packages/lib/test/model/modelDecorator.test.ts

I've suppressed false positive ESLint warnings.

Suppress false positive ESLint warnings

---

CHANGELOG.md
packages/lib/src/parent/findChildren.ts
packages/lib/src/parent/index.ts
packages/lib/test/parent/parent.test.ts
packages/site/src/treeLikeStructure.mdx

Add findChildren

---

CHANGELOG.md
packages/lib/src/context/context.ts
packages/lib/test/context/context.test.ts
packages/site/src/contexts.mdx

context apply

---

packages/site/src/references.mdx

I've updated the docs to include the changes made in #234.

update docs on how to update back-references immediately

---

README.md
packages/site/docs/intro.mdx

This PR updates the CI badge from Circle CI to GitHub Actions.

update CI badge

---

packages/site/docusaurus.config.js

This PR enables sitemap creation which helps search engine crawlers.

enable sitemap creation for docs

---

packages/lib/src/dataModel/utils.ts
packages/lib/src/modelShared/utils.ts

Unless there's some reason to keep those functions around for the future ...

remove unused internal functions

---

packages/lib/src/types/primitiveBased/enum.ts

More accurate and simpler typing of the enum runtime type-checker.

improve enum runtime type-checker typing

---

packages/lib/package.json
yarn.lock

I don't think `netlify-cli` is used anywhere in the `lib` workspace.

remove unused dev dependency

---

packages/lib/src/action/builtInActions.ts

Just a minor internal typing fix.
Actually conceptually the same as #401.

fix internal builtin action typing

---

CHANGELOG.md
packages/lib/src/modelShared/prop.ts
packages/lib/test/model/subclassing.test.ts

Fixes https://github.com/xaviergonz/mobx-keystone/issues/405#issuecomment-1047000482

fix issue related to constructor generics with optional props

---

packages/lib/src/action/middleware.ts
packages/lib/src/snapshot/applySnapshot.ts
packages/lib/src/snapshot/getSnapshot.ts
packages/lib/src/snapshot/internal.ts
packages/lib/src/snapshot/reconcileArraySnapshot.ts
packages/lib/src/treeUtils/deepEquals.ts
packages/lib/src/tweaker/tweak.ts
packages/lib/src/tweaker/tweakFrozen.ts
packages/lib/src/tweaker/tweakPlainObject.ts

TS is happy also without those `any` assertions.

remove unneeded "any" assertions

---

packages/site/docs/installation.mdx

This PR adds documentation about SWC's configuration to the transpiler configurations docs.

add SWC to transpiler configs docs

---

.github/workflows/main.yml

See https://github.com/xaviergonz/mobx-keystone/pull/414#issuecomment-1053742485.

add CI job that tests building the benchmark

---

README.md
packages/site/docs/intro.mdx

An attempt at tuning the "marketing" appearance. :wink: Much inspired by https://github.com/vercel/next.js.

improve badges style and README design

---

README.md

A small fix of my negligence in #425.

fix badge aria label

---

packages/lib/src/types/objectBased/object.ts

Just for consistency ... :wink:

use all lowercase @typeparam tag consistently

---

packages/site/docs/patches.mdx

Here is a small PR to fix #438

docs(patches): fix typo about the number of changes detection ways

---

apps/site/docs/mapsSetsDates.mdx

remove a typo backtick
